---
# Area
- name: area/cmd
  color: "a18fbf" # purple
  description: >-
    Changes made to command line utilities

- name: area/docs
  color: "8fbcbc" # teal
  description: >-
    Changes made to project documentation

- name: area/github
  color: "72ccf3" # blue
  description: >-
    Changes made to github actions

- name: area/pre-commit
  color: "BC9BE3" # lavender
  description: >-
    Changes made to pre-commit hooks

- name: area/go-mod-sum
  color: "7BD7E0" # cyan
  description: >-
    Changes made to go.mod and go.sum

# Renovate
- name: renovate/container
  color: "ffc300" # yellow
- name: renovate/github-action
  color: "ffc300" # yellow
- name: renovate/github-release
  color: "ffc300" # yellow

# Semantic Type
- name: type/digest
  color: "FFEC19" # yellow
- name: type/patch
  color: "FFEC19" # yellow
- name: type/minor
  color: "FF9800" # orange
- name: type/major
  color: "F6412D" # red
- name: type/break
  color: "F6412D" # red

# Uncategorized
- name: bug
  color: "ee0701" # red
- name: do-not-merge
  color: "ee0701" # red
- name: docs
  color: "F4D1B7" # beige
- name: enhancement
  color: "84b6eb" # light blue
- name: question
  description: >-
    Clarification and/or additional information required to move forward
  color: "cc317c" # pink
