---
project_name: guacinator

release:
  github:
    owner: CowDogMoo
    name: guacinator

builds:
  - id: "guacinator"
    binary: guacinator
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v2
      - v3
    env:
      - CGO_ENABLED=0
    goarm:
      - "6"
      - "7"
