---
name: goreleaser
on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    name: Run go releaser
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: "1.20"

      # - name: Install changelog gh cli extension
      #   run: gh extension install chelnak/gh-changelog
      #   env:
      #     GH_TOKEN: ${{ github.token }}

      - name: Fix GOPATH
        run: export PATH=$PATH:$(go env GOPATH)/bin

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
