---
name: Nancy 3p Vulnerability Scan
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  nancy:
    name: Run nancy to identify 3p go vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version: "1.22"

      - name: Write go.list
        run: go list -json -deps ./... > go.list

      - name: Run nancy to check for vulnerabilities
        uses: sonatype-nexus-community/nancy-github-action@main
