---
name: Tests
on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    name: Run tests - includes pre-commit hooks and determining code coverage %
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: "3.x"

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version: "1.20"

      - name: Install goreleaser
        run: go install github.com/goreleaser/goreleaser@latest

      - name: Install pre-commit
        run: pip3 install pre-commit

      - name: Set git config
        run: |
          git config --global user.name "John Doe"
          git config --global user.email johndoe@example.com

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip3 install keepercommander

      - name: Generate the coverage output
        run: |
          bash .hooks/go-unit-tests.sh coverage

      - name: Send the coverage output
        uses: shogo82148/actions-goveralls@785c9d68212c91196d3994652647f8721918ba11 # v1
        with:
          path-to-profile: coverage-all.out
