---
name: Tests
on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    name: Run tests and determine code coverage %
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version: "1.23"
          cache-dependency-path: "**/*.sum"

      - name: Set git config
        run: |
          git config --global user.name "John Doe"
          git config --global user.email johndoe@example.com

      - name: Generate the coverage output
        run: |
          bash .hooks/run-go-tests.sh coverage

      - name: Send the coverage output
        uses: shogo82148/actions-goveralls@e6875f831db61e6abffbd8df91a2eb6cd24b46c9 # v1
        with:
          path-to-profile: coverage-all.out
